const categories = [
    "General Knowledge",
    "Current Affairs",
    "Science and Nature",
    "Technology",
    "Sports",
    "History",
    "Geography",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Algorithms",
    "Data Structures",
    "Operating Systems",
    "Databases",
    "Networking",
    "Artificial Intelligence",
    "Machine Learning",
    "Cybersecurity",
    "Web Development",
    "Mobile Development",
    "Cloud Computing",
    "Blockchain",
    "Economics",
    "Literature",
    "Political Science",
    "Movies",
    "TV Shows",
    "Music",
    "Celebrities",
    "Books",
    "Health and Fitness",
    "Food and Drinks",
    "Travel",
    "Fashion",
    "Hobbies",
    "Vocabulary",
    "Grammar",
    "Poetry",
    "Mythology",
    "Famous Authors",
    "Comics and Manga",
    "Video Games",
    "Anime",
    "Cartoons",
    "Stand-Up Comedy",
    "Cricket",
    "Football (Soccer)",
    "Basketball",
    "Chess",
    "Olympics",
    "World Capitals",
    "Flags and Countries",
    "Religions",
    "Famous Monuments",
    "Festivals",
    "Space and Astronomy",
    "Inventions and Discoveries",
    "Environmental Science",
    "Robotics",
    "Business and Startups",
    "Logical Reasoning",
    "Puzzles and Riddles",
    "IQ Tests",
    "Trivia Challenges"
  ];
  
export default categories;  